spring.application.name=Log-Aggregator
server.port=8080
server.address=0.0.0.0
spring.main.allow-bean-definition-overriding=true

#MongoDB
spring.data.mongodb.uri=${MONGO_URI}


# Kafka
spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS}
spring.kafka.consumer.group-id=${KAFKA_GROUP_ID:log-group}
spring.kafka.consumer.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS}
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.enable-auto-commit=false


#Redis
spring.redis.host=${REDIS_HOST:redis}
spring.redis.port=6379
spring.redis.database=0

# API key
api.auth.token=${API_AUTH_TOKEN}

resilience4j.circuitbreaker.instances.mongoCB.registerHealthIndicator=true
resilience4j.circuitbreaker.instances.mongoCB.slidingWindowSize=5
resilience4j.circuitbreaker.instances.mongoCB.failureRateThreshold=50
resilience4j.circuitbreaker.instances.mongoCB.waitDurationInOpenState=10s
resilience4j.circuitbreaker.instances.mongoCB.automaticTransitionFromOpenToHalfOpenEnabled=true

# Retry
spring.kafka.listener.concurrency=1
spring.kafka.listener.ack-mode=manual

# DLT (Dead Letter Topic)
spring.kafka.consumer.properties.spring.kafka.consumer.retry.backoff.ms=1000
spring.kafka.consumer.properties.max.poll.interval.ms=30000
spring.kafka.consumer.properties.spring.kafka.listener.default-error-handler=false
